version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "backend"
      POSTGRES_USER: "evgeniy"
      POSTGRES_PASSWORD: "testpassword1234"
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command:
      - python3.11 -m flask db init
      - python3.11 -m flask db upgrade
      - python3.11 -m flask db migrate
      - python -m flask run --host=0.0.0.0 -p 8001
    ports:
      - "80:8001"
    depends_on:
      - postgres
volumes:
  postgres_data: