version: "3"
services:

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "backend"
      POSTGRES_USER: "evgeniy"
      POSTGRES_PASSWORD: "testpassword1234"
    ports:
      - "5432:5432"

  backend:
    build: ./
    volumes:
      - backend_data:/usr/src/app/migrations
    ports:
      - "80:5000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always
volumes:
  postgres_data:
  backend_data: