version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "backend"
      POSTGRES_USER: "evgeniy"
      POSTGRES_PASSWORD: "testpassword1234"
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: ./
    volumes:
      - backend_data:/usr/src/app/migrations
    ports:
      - "80:5000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always

  elastic:
    container_name: elastic
    image: elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    hostname: vhdocker
    volumes:
      - '/var/lib:/var/lib'
      - '/dev/net/tun:/dev/net/tun'
    network_mode: host
    env_file:
      - ./ts.env

#  logstash:
#    container_name: logstash
#    image: logstash:8.7.0
#    ports:
#      - "5064:5064"

volumes:
  postgres_data:
  backend_data:
  elasticsearch-data:
    driver: local