version: "3"
services:
  backend:
    build: /
    ports:
      - "80:8001"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "evgeniy"
      POSTGRES_PASSWORD: "testpassword1234"
    ports:
      - "5432:5432"